### ISSUE TITLE
Feature: Radio Channel Management with qb-radio

### ISSUE THREAD

**Issue by burnoutprojects** [Swift-peak-hosting-dev/qb-radio#2]
# Current Status:  🚧 WIP

## Description
Currently I rewrote the [qb-radio](https://github.com/qbcore-framework/qb-radio) script to implement some core missing functions for communication with SnailyCAD API. After the development process and release of the new modified version of the script, you have to remove the original `qb-radio` script and add our script if you want to use with SnailyCAD instance.

## TODO
- [ ] qb-radio
  - [x] Add event emit on channel change
  - [ ] Fix some small UI bugs
- [ ] sna-radio
  - [ ] Listen for radio channel changes
  - [ ] Send channel to SnailyCAD API
  - [ ] Listen for SnailyCAD API channel changes (websocket)
 
## External issues
https://github.com/SnailyCAD/snaily-cadv4/issues/1917
